import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import  MainComponent  from '@/components/Body/main-component'
import React from 'react';




const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  // const date = new Date()

  // data['date'] = date
  return (
    <div className={styles.container}>
      <Head>
        <title>Events | App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HearderNav /> */}
      <MainComponent data={data} />
      {/* <Footer data = {data} /> */}
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('../../data/data.json');
  console.log(events_categories);
  return {
    props: {
      data: events_categories
    }
  }

}
